import type { Caregiver } from "@/types";

export const MOCK_CAREGIVERS: Caregiver[] = [
  {
    id: "1",
    name: "Rukhsar",
    gender: "female",
    category: "qualified_nurse",
    city: "Lahore",
    bio: "A dedicated and compassionate qualified nurse committed to providing professional home care with warmth and diligence.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    services: ["post_op_care", "elderly_care", "night_duty"],
  },
  {
    id: "2",
    name: "Sara",
    gender: "female",
    category: "qualified_nurse",
    city: "Lahore",
    bio: "A caring and skilled qualified nurse with a calm, patient-focused approach to home nursing care.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    services: ["paediatric_care", "elderly_care", "night_duty"],
  },
  {
    id: "3",
    name: "Rashid",
    gender: "male",
    category: "qualified_nurse",
    city: "Lahore",
    bio: "A professional and experienced qualified nurse focused on post-operative and chronic condition care at home.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    services: ["post_op_care", "diabetic_care", "night_duty"],
  },
  {
    id: "4",
    name: "Zohaib",
    gender: "male",
    category: "qualified_nurse",
    city: "Lahore",
    bio: "A dependable and skilled qualified nurse known for his attentive care and professional bedside manner.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    services: ["elderly_care", "post_op_care", "night_duty"],
  },
  {
    id: "5",
    name: "Bushra",
    gender: "female",
    category: "attendant",
    city: "Lahore",
    bio: "A warm and reliable female attendant providing personal care, hygiene support, and companionship for patients at home.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    services: ["elderly_care", "paediatric_care", "night_duty"],
  },
  {
    id: "6",
    name: "Jamil",
    gender: "male",
    category: "attendant",
    city: "Lahore",
    bio: "A trained and trustworthy male attendant experienced in patient handling, hygiene assistance, and daily care routines.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    services: ["elderly_care", "night_duty"],
  },
];
