import type { Caregiver, Review } from "@/types";

export const MOCK_CAREGIVERS: Caregiver[] = [
  {
    id: "1",
    name: "Sana Malik",
    gender: "female",
    category: "qualified_nurse",
    pnc_number: "PNC-2019-04821",
    city: "Lahore",
    experience_years: 6,
    bio: "Experienced post-operative and ICU step-down nurse with 6 years in top Lahore hospitals. Passionate about patient recovery and family education.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    rating_avg: 4.9,
    review_count: 47,
    services: ["post_op_care", "icu_stepdown", "night_duty"],
    specialisations: ["Post-op Care", "ICU Step-down", "Night Duty"],
  },
  {
    id: "2",
    name: "Ahmed Raza",
    gender: "male",
    category: "qualified_nurse",
    pnc_number: "PNC-2017-03156",
    city: "Karachi",
    experience_years: 8,
    bio: "Senior male nurse specialising in diabetic care and elderly management. Previously worked at Aga Khan Hospital for 5 years.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    rating_avg: 4.8,
    review_count: 62,
    services: ["diabetic_care", "elderly_care", "paediatric_care"],
    specialisations: ["Diabetic Care", "Elderly Care", "Paediatric Care"],
  },
  {
    id: "3",
    name: "Fatima Zahra",
    gender: "female",
    category: "qualified_nurse",
    pnc_number: "PNC-2021-06734",
    city: "Islamabad",
    experience_years: 4,
    bio: "Certified paediatric nurse with expertise in neonatal and infant care. Gentle, patient, and highly recommended by families.",
    is_available: true,
    availability_status: "available_today",
    is_verified: true,
    rating_avg: 4.9,
    review_count: 31,
    services: ["paediatric_care", "night_duty", "elderly_care"],
    specialisations: ["Paediatric Care", "Night Duty", "Elderly Care"],
  },
  {
    id: "4",
    name: "Usman Khan",
    gender: "male",
    category: "attendant",
    city: "Lahore",
    experience_years: 3,
    bio: "Trained male attendant specialising in elderly care and night duty. Calm, dependable, and trusted by over 50 families in Lahore.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    rating_avg: 4.7,
    review_count: 28,
    services: ["elderly_care", "night_duty"],
    specialisations: ["Elderly Care", "Night Duty"],
  },
  {
    id: "5",
    name: "Nadia Hussain",
    gender: "female",
    category: "attendant",
    city: "Karachi",
    experience_years: 5,
    bio: "Experienced female attendant with a background in childcare and elderly support. Known for her warm, compassionate approach.",
    is_available: true,
    availability_status: "available_today",
    is_verified: true,
    rating_avg: 4.8,
    review_count: 39,
    services: ["elderly_care", "paediatric_care", "night_duty"],
    specialisations: ["Elderly Care", "Paediatric Care", "Night Duty"],
  },
  {
    id: "6",
    name: "Bilal Chaudhry",
    gender: "male",
    category: "qualified_nurse",
    pnc_number: "PNC-2018-04290",
    city: "Rawalpindi",
    experience_years: 7,
    bio: "Male qualified nurse with extensive ICU and post-op experience. Fluent in medical terminology and family counselling.",
    is_available: false,
    availability_status: "unavailable",
    is_verified: true,
    rating_avg: 4.6,
    review_count: 55,
    services: ["post_op_care", "icu_stepdown", "diabetic_care"],
    specialisations: ["Post-op Care", "ICU Step-down", "Diabetic Care"],
  },
  {
    id: "7",
    name: "Ayesha Siddiqui",
    gender: "female",
    category: "qualified_nurse",
    pnc_number: "PNC-2020-05511",
    city: "Faisalabad",
    experience_years: 5,
    bio: "Qualified nurse focused on night duty and elderly care. Available for extended stays and live-in arrangements.",
    is_available: true,
    availability_status: "available_now",
    is_verified: true,
    rating_avg: 4.7,
    review_count: 22,
    services: ["night_duty", "elderly_care", "diabetic_care"],
    specialisations: ["Night Duty", "Elderly Care", "Diabetic Care"],
  },
  {
    id: "8",
    name: "Tariq Mehmood",
    gender: "male",
    category: "attendant",
    city: "Islamabad",
    experience_years: 4,
    bio: "Professional male attendant trained in patient handling, hygiene care, and physiotherapy assistance.",
    is_available: true,
    availability_status: "available_today",
    is_verified: true,
    rating_avg: 4.5,
    review_count: 18,
    services: ["elderly_care", "night_duty", "paediatric_care"],
    specialisations: ["Elderly Care", "Night Duty", "Paediatric Care"],
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    booking_id: "b1",
    user_id: "u1",
    caregiver_id: "1",
    rating: 5,
    comment: "Sana was absolutely wonderful with my father post-surgery. Professional, punctual, and very gentle. Highly recommended!",
    user_name: "Kamran Ahmed",
    created_at: "2025-04-10",
  },
  {
    id: "r2",
    booking_id: "b2",
    user_id: "u2",
    caregiver_id: "1",
    rating: 5,
    comment: "Best home nursing service I have used. The nurse was knowledgeable and my mother recovered faster than expected.",
    user_name: "Sara Hussain",
    created_at: "2025-03-22",
  },
  {
    id: "r3",
    booking_id: "b3",
    user_id: "u3",
    caregiver_id: "2",
    rating: 5,
    comment: "Ahmed Raza is extremely professional. Managed my husband's diabetes care perfectly for two weeks.",
    user_name: "Rabia Khan",
    created_at: "2025-04-01",
  },
];

export const MOCK_TESTIMONIALS = [
  {
    name: "Kamran Ahmed",
    city: "Lahore",
    rating: 5,
    quote: "SehatGhar connected us with a fantastic nurse within 2 hours. My father's post-op recovery was smooth and stress-free. Worth every rupee.",
  },
  {
    name: "Sara Hussain",
    city: "Karachi",
    rating: 5,
    quote: "As a family, finding a trustworthy female nurse was our biggest concern. SehatGhar's verification process gave us complete peace of mind.",
  },
  {
    name: "Dr. Imran Baig",
    city: "Islamabad",
    rating: 5,
    quote: "I recommend SehatGhar to all my patients who need home care after discharge. The nurses are PNC-certified and truly professional.",
  },
];
